apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-guestbook
  template:
    metadata:
      labels:
        app: php-guestbook
    spec:
      containers:
      - name: php-guestbook
        image: docker.io/waveywaves/mirrord-php-example:v5
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379" 